import type { ModelInfo, VendorConfig } from "./types.js";

// ─── DeepSeek ────────────────────────────────────────────────────────────────

const DEEPSEEK_BASE_URL = "https://api.deepseek.com/v1";

const DEEPSEEK_MODELS: ModelInfo[] = [
	{
		id: "deepseek-v4-flash",
		name: "DeepSeek V4 Flash",
		family: "deepseek",
		version: "v4-flash",
		tooltip: "DeepSeek V4 Flash — fast, general-purpose reasoning model",
		maxInputTokens: 1000000,
		maxOutputTokens: 384000,
		baseUrl: DEEPSEEK_BASE_URL,
		thinking: true,
		thinkingEffortSupport: true,
		capabilities: { imageInput: false, toolCalling: true },
	},
	{
		id: "deepseek-v4-pro",
		name: "DeepSeek V4 Pro",
		family: "deepseek",
		version: "v4-pro",
		tooltip: "DeepSeek V4 Pro — most capable reasoning model",
		maxInputTokens: 1000000,
		maxOutputTokens: 384000,
		baseUrl: DEEPSEEK_BASE_URL,
		thinking: true,
		thinkingEffortSupport: true,
		capabilities: { imageInput: false, toolCalling: true },
	},
	{
		id: "deepseek-v4-flash-vision-exp",
		name: "DeepSeek V4 Flash Vision (Exp)",
		family: "deepseek",
		version: "v4-flash-vision-exp",
		tooltip: "DeepSeek V4 Flash Vision (Exp) — experimental multimodal model, vision support",
		maxInputTokens: 1000000,
		maxOutputTokens: 384000,
		baseUrl: DEEPSEEK_BASE_URL,
		thinking: true,
		thinkingEffortSupport: true,
		capabilities: { imageInput: true, toolCalling: true },
	},
];

// ─── GLM Coding Plan CN ────────────────────────────────────────────────────────

const ZHIPU_BASE_URL = "https://open.bigmodel.cn/api/coding/paas/v4";

const ZHIPU_MODELS: ModelInfo[] = [
	{
		id: "glm-5.3",
		name: "GLM-5.3",
		family: "glm",
		version: "5.3",
		tooltip: "GLM-5.3 — flagship, thinking always on, 1M context",
		maxInputTokens: 1000000,
		maxOutputTokens: 131072,
		baseUrl: ZHIPU_BASE_URL,
		thinking: true,
		thinkingEffortSupport: true,
		capabilities: { imageInput: false, toolCalling: true },
	},
	{
		id: "glm-5.3-flash",
		name: "GLM-5.3 Flash",
		family: "glm",
		version: "5.3-flash",
		tooltip: "GLM-5.3 Flash — fast multimodal flagship, thinking always on, vision support",
		maxInputTokens: 1000000,
		maxOutputTokens: 131072,
		baseUrl: ZHIPU_BASE_URL,
		thinking: true,
		thinkingEffortSupport: true,
		capabilities: { imageInput: true, toolCalling: true },
	},
];

// ─── Kimi Code Plan ──────────────────────────────────────────────────────────

const KIMI_CODING_BASE_URL = "https://api.kimi.com/coding/v1";

// ─── Moonshot Open Platform ──────────────────────────────────────────────────

const KIMI_OPEN_BASE_URL = "https://api.moonshot.cn/v1";

const MOONSHOT_MODELS: ModelInfo[] = [
	{
		id: "k3",
		name: "Kimi K3",
		family: "kimi",
		version: "k3",
		tooltip: "Kimi K3 — 2.8T flagship, 1M context (requires Allegretto+ plan), vision support",
		maxInputTokens: 1000000,
		// max_completion_tokens is configurable up to the 1M context window
		// (default 131072), so max output equals max input for K3.
		maxOutputTokens: 1048576,
		baseUrl: KIMI_CODING_BASE_URL,
		thinking: true,
		thinkingEffortSupport: true,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "k3-256k",
		name: "Kimi K3 256K",
		family: "kimi",
		version: "k3-256k",
		tooltip: "Kimi K3 256K — same K3 within 256K context, roughly half the consumption",
		maxInputTokens: 262144,
		// Mirrors k3: output can span the full 256K window (inferred, same
		// "output = context" behavior as k3 on the Code endpoint).
		maxOutputTokens: 262144,
		baseUrl: KIMI_CODING_BASE_URL,
		thinking: true,
		thinkingEffortSupport: true,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "kimi-for-coding",
		name: "Kimi for Coding",
		family: "kimi",
		version: "for-coding",
		tooltip: "Kimi for Coding — K2.7 Code, thinking always on, vision support",
		maxInputTokens: 262144,
		maxOutputTokens: 32768,
		baseUrl: KIMI_CODING_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		thinkingLocked: true,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "kimi-for-coding-highspeed",
		name: "Kimi for Coding HighSpeed",
		family: "kimi",
		version: "for-coding-highspeed",
		tooltip: "Kimi for Coding HighSpeed — K2.7 Code at 5-6x speed, ~3x consumption",
		maxInputTokens: 262144,
		maxOutputTokens: 32768,
		baseUrl: KIMI_CODING_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		thinkingLocked: true,
		capabilities: { imageInput: true, toolCalling: true },
	},
];

const MOONSHOT_OPEN_MODELS: ModelInfo[] = [
	{
		id: "kimi-k3",
		name: "Kimi K3",
		family: "kimi",
		version: "k3",
		tooltip: "Kimi K3 — 2.8T flagship, 1M context, thinking always on, vision support",
		maxInputTokens: 1000000,
		// max_completion_tokens is configurable up to the 1M context window
		// (default 131072), so max output equals max input for K3.
		maxOutputTokens: 1048576,
		baseUrl: KIMI_OPEN_BASE_URL,
		thinking: true,
		thinkingEffortSupport: true,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "kimi-k2.7-code",
		name: "Kimi K2.7 Code",
		family: "kimi",
		version: "k2.7-code",
		tooltip: "Kimi K2.7 Code — coding model, thinking always on, vision support",
		maxInputTokens: 262144,
		maxOutputTokens: 32768,
		baseUrl: KIMI_OPEN_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		thinkingLocked: true,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "kimi-k2.7-code-highspeed",
		name: "Kimi K2.7 Code HighSpeed",
		family: "kimi",
		version: "k2.7-code-highspeed",
		tooltip: "Kimi K2.7 Code HighSpeed — ~180 tokens/s output, thinking always on, vision support",
		maxInputTokens: 262144,
		maxOutputTokens: 32768,
		baseUrl: KIMI_OPEN_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		thinkingLocked: true,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "kimi-k2.6",
		name: "Kimi K2.6",
		family: "kimi",
		version: "k2.6",
		tooltip: "Kimi K2.6 — vision and text input, thinking and non-thinking modes",
		maxInputTokens: 262144,
		maxOutputTokens: 32768,
		baseUrl: KIMI_OPEN_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		capabilities: { imageInput: true, toolCalling: true },
	},
];

// ─── Qwen Token Plan ─────────────────────────────────────────────────────────

const QWEN_TOKEN_PLAN_BASE_URL = "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1";

const QWEN_MODELS: ModelInfo[] = [
	{
		id: "qwen3.8-max",
		name: "Qwen3.8 Max",
		family: "qwen",
		version: "3.8-max",
		tooltip: "Qwen3.8 Max — 2.4T MoE flagship, 1M context, vision support",
		maxInputTokens: 1000000,
		maxOutputTokens: 131072,
		baseUrl: QWEN_TOKEN_PLAN_BASE_URL,
		thinking: true,
		thinkingEffortSupport: true,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "qwen3.8-flash",
		name: "Qwen3.8 Flash",
		family: "qwen",
		version: "3.8-flash",
		tooltip: "Qwen3.8 Flash — fast multimodal model, native 1M context, vision support",
		maxInputTokens: 1000000,
		maxOutputTokens: 131072,
		baseUrl: QWEN_TOKEN_PLAN_BASE_URL,
		thinking: true,
		thinkingEffortSupport: true,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "qwen3.7-max",
		name: "Qwen3.7 Max",
		family: "qwen",
		version: "3.7-max",
		tooltip: "Qwen3.7 Max — text flagship, 1M context",
		maxInputTokens: 1000000,
		maxOutputTokens: 131072,
		baseUrl: QWEN_TOKEN_PLAN_BASE_URL,
		thinking: true,
		thinkingEffortSupport: true,
		capabilities: { imageInput: false, toolCalling: true },
	},
	{
		id: "qwen3.7-plus",
		name: "Qwen3.7 Plus",
		family: "qwen",
		version: "3.7-plus",
		tooltip: "Qwen3.7 Plus — balanced performance/cost, 1M context, vision support",
		maxInputTokens: 1000000,
		maxOutputTokens: 131072,
		baseUrl: QWEN_TOKEN_PLAN_BASE_URL,
		thinking: true,
		thinkingEffortSupport: true,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "qwen3.6-flash",
		name: "Qwen3.6 Flash",
		family: "qwen",
		version: "3.6-flash",
		tooltip: "Qwen3.6 Flash — lightweight native-vision model, 1M context, vision support",
		maxInputTokens: 1000000,
		maxOutputTokens: 65536,
		baseUrl: QWEN_TOKEN_PLAN_BASE_URL,
		thinking: true,
		thinkingEffortSupport: true,
		capabilities: { imageInput: true, toolCalling: true },
	},
	// Third-party models hosted on Qwen Token Plan — billed against the
	// plan's Credits instead of the vendor's own API. Thinking goes through
	// the Qwen-style enable_thinking/thinking_budget params, which
	// DashScope-hosted GLM and DeepSeek models accept.
	{
		id: "glm-5.2",
		name: "GLM-5.2 (Token Plan)",
		family: "qwen",
		version: "glm-5.2",
		tooltip: "GLM-5.2 — via Qwen Token Plan, 1M context",
		maxInputTokens: 1000000,
		maxOutputTokens: 131072,
		baseUrl: QWEN_TOKEN_PLAN_BASE_URL,
		thinking: true,
		thinkingEffortSupport: true,
		capabilities: { imageInput: false, toolCalling: true },
	},
	{
		id: "deepseek-v4-pro",
		name: "DeepSeek V4 Pro (Token Plan)",
		family: "qwen",
		version: "deepseek-v4-pro",
		tooltip: "DeepSeek V4 Pro — via Qwen Token Plan, 1M context",
		maxInputTokens: 1000000,
		// DashScope-hosted DeepSeek V4 shares a 393,216-token pool between
		// max_tokens and thinking_budget.
		maxOutputTokens: 393216,
		baseUrl: QWEN_TOKEN_PLAN_BASE_URL,
		thinking: true,
		thinkingEffortSupport: true,
		capabilities: { imageInput: false, toolCalling: true },
	},
	{
		id: "deepseek-v4-pro-0813",
		name: "DeepSeek V4 Pro 0813 (Token Plan)",
		family: "qwen",
		version: "deepseek-v4-pro-0813",
		tooltip: "DeepSeek V4 Pro 0813 — via Qwen Token Plan, 1M context",
		maxInputTokens: 1000000,
		maxOutputTokens: 393216,
		baseUrl: QWEN_TOKEN_PLAN_BASE_URL,
		thinking: true,
		thinkingEffortSupport: true,
		capabilities: { imageInput: false, toolCalling: true },
	},
	{
		id: "deepseek-v4-flash-0731",
		name: "DeepSeek V4 Flash 0731 (Token Plan)",
		family: "qwen",
		version: "deepseek-v4-flash-0731",
		tooltip: "DeepSeek V4 Flash 0731 — via Qwen Token Plan, 1M context",
		maxInputTokens: 1000000,
		maxOutputTokens: 393216,
		baseUrl: QWEN_TOKEN_PLAN_BASE_URL,
		thinking: true,
		thinkingEffortSupport: true,
		capabilities: { imageInput: false, toolCalling: true },
	},
];

// ─── MiniMax ─────────────────────────────────────────────────────────────────

const MINIMAX_BASE_URL = "https://api.minimaxi.com/v1";

const MINIMAX_MODELS: ModelInfo[] = [
	{
		id: "MiniMax-M3",
		name: "MiniMax M3",
		family: "minimax",
		version: "m3",
		tooltip: "MiniMax M3 — 1M context multimodal flagship, vision support",
		maxInputTokens: 1000000,
		// 512K max output per the MiniMax docs (thinking + answer share it).
		maxOutputTokens: 524288,
		baseUrl: MINIMAX_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "MiniMax-M2.7",
		name: "MiniMax M2.7",
		family: "minimax",
		version: "m2.7",
		tooltip: "MiniMax M2.7 — interleaved thinking flagship model, thinking always on",
		maxInputTokens: 204800,
		maxOutputTokens: 131072,
		baseUrl: MINIMAX_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		thinkingLocked: true,
		capabilities: { imageInput: false, toolCalling: true },
	},
	{
		id: "MiniMax-M2.7-highspeed",
		name: "MiniMax M2.7 HighSpeed",
		family: "minimax",
		version: "m2.7-highspeed",
		tooltip: "MiniMax M2.7 HighSpeed — fast interleaved thinking, thinking always on",
		maxInputTokens: 204800,
		maxOutputTokens: 131072,
		baseUrl: MINIMAX_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		thinkingLocked: true,
		capabilities: { imageInput: false, toolCalling: true },
	},
	{
		id: "MiniMax-M2.5",
		name: "MiniMax M2.5",
		family: "minimax",
		version: "m2.5",
		tooltip: "MiniMax M2.5 — interleaved thinking balanced model, thinking always on",
		maxInputTokens: 204800,
		maxOutputTokens: 131072,
		baseUrl: MINIMAX_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		thinkingLocked: true,
		capabilities: { imageInput: false, toolCalling: true },
	},
];

// ─── Volcengine Coding Plan ──────────────────────────────────────────────────

const VOLCENGINE_CODING_BASE_URL = "https://ark.cn-beijing.volces.com/api/coding/v3";

// ─── Volcengine Agent Plan ───────────────────────────────────────────────────

const VOLCENGINE_AGENT_BASE_URL = "https://ark.cn-beijing.volces.com/api/plan/v3";

// Coding Plan models (api/coding/v3).
const VOLCENGINE_CODING_MODELS: ModelInfo[] = [
	{
		id: "doubao-seed-2.0-lite",
		name: "Doubao Seed 2.0 Lite",
		family: "volcengine",
		version: "seed-2.0-lite",
		tooltip: "Doubao Seed 2.0 Lite — lightweight model, 256K context, vision support, thinking on by default",
		maxInputTokens: 262144,
		maxOutputTokens: 131072,
		baseUrl: VOLCENGINE_CODING_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "kimi-k2.7-code",
		name: "Kimi K2.7 Code (Volcengine)",
		family: "volcengine",
		version: "kimi-k2.7-code",
		tooltip: "Kimi K2.7 Code — via Volcengine Coding Plan, thinking always on, vision support",
		maxInputTokens: 262144,
		maxOutputTokens: 32768,
		baseUrl: VOLCENGINE_CODING_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		thinkingLocked: true,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "minimax-m3",
		name: "MiniMax M3 (Volcengine)",
		family: "volcengine",
		version: "minimax-m3",
		tooltip: "MiniMax M3 — via Volcengine Coding Plan, 1M context, vision support",
		maxInputTokens: 1000000,
		maxOutputTokens: 524288,
		baseUrl: VOLCENGINE_CODING_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "doubao-seed-2.1-turbo",
		name: "Doubao Seed 2.1 Turbo",
		family: "volcengine",
		version: "seed-2.1-turbo",
		tooltip: "Doubao Seed 2.1 Turbo — efficient flagship, multimodal input, thinking on by default",
		maxInputTokens: 262144,
		maxOutputTokens: 131072,
		baseUrl: VOLCENGINE_CODING_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "deepseek-v4-flash",
		name: "DeepSeek V4 Flash (Volcengine)",
		family: "volcengine",
		version: "deepseek-v4-flash",
		tooltip: "DeepSeek V4 Flash — via Volcengine Coding Plan, 1M context",
		maxInputTokens: 1000000,
		maxOutputTokens: 384000,
		baseUrl: VOLCENGINE_CODING_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		capabilities: { imageInput: false, toolCalling: true },
	},
	{
		id: "glm-5.3",
		name: "GLM-5.3 (Volcengine)",
		family: "volcengine",
		version: "glm-5.3",
		tooltip: "GLM-5.3 — via Volcengine Coding Plan, 1M context, thinking always on",
		maxInputTokens: 1000000,
		maxOutputTokens: 131072,
		baseUrl: VOLCENGINE_CODING_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		thinkingLocked: true,
		capabilities: { imageInput: false, toolCalling: true },
	},
	{
		id: "doubao-seed-evolving",
		name: "Doubao Seed Evolving",
		family: "volcengine",
		version: "seed-evolving",
		tooltip: "Doubao Seed Evolving — self-evolving agent model for long-horizon coding and agentic tasks",
		maxInputTokens: 262144,
		maxOutputTokens: 131072,
		baseUrl: VOLCENGINE_CODING_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "deepseek-v4-pro",
		name: "DeepSeek V4 Pro (Volcengine)",
		family: "volcengine",
		version: "deepseek-v4-pro",
		tooltip: "DeepSeek V4 Pro — via Volcengine Coding Plan, 1M context",
		maxInputTokens: 1000000,
		maxOutputTokens: 384000,
		baseUrl: VOLCENGINE_CODING_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		capabilities: { imageInput: false, toolCalling: true },
	},
	{
		id: "glm-5.3-flash",
		name: "GLM-5.3 Flash (Volcengine)",
		family: "volcengine",
		version: "glm-5.3-flash",
		tooltip: "GLM-5.3 Flash — via Volcengine Coding Plan, 1M context, vision support, thinking always on",
		maxInputTokens: 1000000,
		maxOutputTokens: 131072,
		baseUrl: VOLCENGINE_CODING_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		thinkingLocked: true,
		capabilities: { imageInput: true, toolCalling: true },
	},
];

// Agent Plan models (api/plan/v3) — the Coding Plan set plus
// doubao-seed-2.0-mini and kimi-k3.
const VOLCENGINE_AGENT_MODELS: ModelInfo[] = [
	{
		id: "doubao-seed-2.0-lite",
		name: "Doubao Seed 2.0 Lite",
		family: "volcengine",
		version: "seed-2.0-lite",
		tooltip: "Doubao Seed 2.0 Lite — lightweight model, 256K context, vision support, thinking on by default",
		maxInputTokens: 262144,
		maxOutputTokens: 131072,
		baseUrl: VOLCENGINE_AGENT_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "doubao-seed-2.0-mini",
		name: "Doubao Seed 2.0 Mini",
		family: "volcengine",
		version: "seed-2.0-mini",
		tooltip: "Doubao Seed 2.0 Mini — compact agent model, thinking on by default",
		maxInputTokens: 262144,
		maxOutputTokens: 65536,
		baseUrl: VOLCENGINE_AGENT_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "kimi-k2.7-code",
		name: "Kimi K2.7 Code (Volcengine)",
		family: "volcengine",
		version: "kimi-k2.7-code",
		tooltip: "Kimi K2.7 Code — via Volcengine Agent Plan, thinking always on, vision support",
		maxInputTokens: 262144,
		maxOutputTokens: 32768,
		baseUrl: VOLCENGINE_AGENT_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		thinkingLocked: true,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "minimax-m3",
		name: "MiniMax M3 (Volcengine)",
		family: "volcengine",
		version: "minimax-m3",
		tooltip: "MiniMax M3 — via Volcengine Agent Plan, 1M context, vision support",
		maxInputTokens: 1000000,
		maxOutputTokens: 524288,
		baseUrl: VOLCENGINE_AGENT_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "doubao-seed-evolving",
		name: "Doubao Seed Evolving",
		family: "volcengine",
		version: "seed-evolving",
		tooltip: "Doubao Seed Evolving — self-evolving agent model for long-horizon coding and agentic tasks",
		maxInputTokens: 262144,
		maxOutputTokens: 131072,
		baseUrl: VOLCENGINE_AGENT_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "kimi-k3",
		name: "Kimi K3 (Volcengine)",
		family: "volcengine",
		version: "kimi-k3",
		tooltip: "Kimi K3 — via Volcengine Agent Plan, 1M context, vision support, thinking always on",
		maxInputTokens: 1000000,
		maxOutputTokens: 1048576,
		baseUrl: VOLCENGINE_AGENT_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		thinkingLocked: true,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "doubao-seed-2.1-turbo",
		name: "Doubao Seed 2.1 Turbo",
		family: "volcengine",
		version: "seed-2.1-turbo",
		tooltip: "Doubao Seed 2.1 Turbo — efficient flagship, multimodal input, thinking on by default",
		maxInputTokens: 262144,
		maxOutputTokens: 131072,
		baseUrl: VOLCENGINE_AGENT_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		capabilities: { imageInput: true, toolCalling: true },
	},
	{
		id: "deepseek-v4-flash",
		name: "DeepSeek V4 Flash (Volcengine)",
		family: "volcengine",
		version: "deepseek-v4-flash",
		tooltip: "DeepSeek V4 Flash — via Volcengine Agent Plan, 1M context",
		maxInputTokens: 1000000,
		maxOutputTokens: 384000,
		baseUrl: VOLCENGINE_AGENT_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		capabilities: { imageInput: false, toolCalling: true },
	},
	{
		id: "glm-5.3",
		name: "GLM-5.3 (Volcengine)",
		family: "volcengine",
		version: "glm-5.3",
		tooltip: "GLM-5.3 — via Volcengine Agent Plan, 1M context, thinking always on",
		maxInputTokens: 1000000,
		maxOutputTokens: 131072,
		baseUrl: VOLCENGINE_AGENT_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		thinkingLocked: true,
		capabilities: { imageInput: false, toolCalling: true },
	},
	{
		id: "deepseek-v4-pro",
		name: "DeepSeek V4 Pro (Volcengine)",
		family: "volcengine",
		version: "deepseek-v4-pro",
		tooltip: "DeepSeek V4 Pro — via Volcengine Agent Plan, 1M context",
		maxInputTokens: 1000000,
		maxOutputTokens: 384000,
		baseUrl: VOLCENGINE_AGENT_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		capabilities: { imageInput: false, toolCalling: true },
	},
	{
		id: "glm-5.3-flash",
		name: "GLM-5.3 Flash (Volcengine)",
		family: "volcengine",
		version: "glm-5.3-flash",
		tooltip: "GLM-5.3 Flash — via Volcengine Agent Plan, 1M context, vision support, thinking always on",
		maxInputTokens: 1000000,
		maxOutputTokens: 131072,
		baseUrl: VOLCENGINE_AGENT_BASE_URL,
		thinking: true,
		thinkingEffortSupport: false,
		thinkingLocked: true,
		capabilities: { imageInput: true, toolCalling: true },
	},
];

// ─── All Vendors ─────────────────────────────────────────────────────────────

export const VENDOR_CONFIGS: VendorConfig[] = [
	{
		vendorId: "deepseek",
		displayName: "DeepSeek",
		defaultBaseUrl: DEEPSEEK_BASE_URL,
		models: DEEPSEEK_MODELS,
		thinkingCapable: true,
	},
	{
		vendorId: "glm-coding-plan-cn",
		displayName: "GLM Coding Plan CN",
		defaultBaseUrl: ZHIPU_BASE_URL,
		models: ZHIPU_MODELS,
		thinkingCapable: true,
	},
	{
		vendorId: "moonshot",
		displayName: "Kimi Code Plan",
		defaultBaseUrl: KIMI_CODING_BASE_URL,
		models: MOONSHOT_MODELS,
		thinkingCapable: true,
	},
	{
		vendorId: "moonshot-open",
		displayName: "Moonshot (Open Platform)",
		defaultBaseUrl: KIMI_OPEN_BASE_URL,
		models: MOONSHOT_OPEN_MODELS,
		thinkingCapable: true,
	},
	{
		vendorId: "qwen",
		displayName: "Qwen Token Plan",
		defaultBaseUrl: QWEN_TOKEN_PLAN_BASE_URL,
		models: QWEN_MODELS,
		thinkingCapable: true,
	},
	{
		vendorId: "minimax",
		displayName: "MiniMax Token Plan CN",
		defaultBaseUrl: MINIMAX_BASE_URL,
		models: MINIMAX_MODELS,
		thinkingCapable: true,
	},
	{
		vendorId: "volcengine",
		displayName: "Volcengine Coding Plan CN",
		defaultBaseUrl: VOLCENGINE_CODING_BASE_URL,
		models: VOLCENGINE_CODING_MODELS,
		thinkingCapable: true,
	},
	{
		vendorId: "volcengine-agent-plan",
		displayName: "Volcengine Agent Plan CN",
		defaultBaseUrl: VOLCENGINE_AGENT_BASE_URL,
		models: VOLCENGINE_AGENT_MODELS,
		thinkingCapable: true,
	},
];

export function getVendorConfig(vendorId: string): VendorConfig | undefined {
	return VENDOR_CONFIGS.find((v) => v.vendorId === vendorId);
}
